### PR TITLE
Add nullable to HasScopeHandler.cs

### PR DESCRIPTION
**Pull request by MRmlik12**
Hello, I noticed on Auth0 ASP.NET Core sample project doesn't have nullable support for file HasScopeHandler.cs, so I'm edited a few lines of code to support this feature

### CODE REVIEW

**Comment by MRmlik12** [comment]
Hello, it's repo alive?

**Comment by frederikprijck** [comment]
Hi,

Could you elaborate on why this change is needed? When opening PRs, it is always helpful to provide context on why a certain change is required, allowing us to get a better understanding of the intention.

Thanks!

**Comment by MRmlik12** [comment]
The goal of this pr is to add nullable feature from C# 8.0 to avoid trowing exception if `scopes` value is null

**Comment by frederikprijck** [comment]
Yes, I understand what this PR is changing but I am curious to understand why the change is needed. Like, why is `scopes` null?
This example is used to accompany our quickstart https://auth0.com/docs/quickstart/backend/aspnet-core-webapi, and I believe in that situation `scope` isn't null.

It would be helpful for me to understand what is causing `scopes` to be null in your case.

**Pull request closed without merging**
